-- AlterTable
ALTER TABLE "BusinessUnit" ADD COLUMN     "Active" BOOLEAN DEFAULT true,
ADD COLUMN     "CreateBy" VARCHAR(100),
ADD COLUMN     "CreateDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "UpdateBy" VARCHAR(100),
ADD COLUMN     "UpdateDate" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Companys" ALTER COLUMN "CreateBy" DROP NOT NULL,
ALTER COLUMN "CreateBy" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "UpdateBy" SET DATA TYPE VARCHAR(100);
