pipelines:

  branches:
    master:
    - step:
        services:
          - docker
        name: Deploy Backend to Registry
        script:
        - cd backend
        - export IMAGE_NAME=hanthamarats/pcl-api:$BITBUCKET_COMMIT
        - docker build -t $IMAGE_NAME -f Dockerfile.prod .
        - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
        - docker push $IMAGE_NAME

    - step:
        services:
          - docker
        image: node:20-slim
        caches:
          - node
        name: Deploy Frontend to Registry
        size: 2x
        script:
          - cd frontend
          - npm install
          - npm run build
          - export IMAGE_NAME=hanthamarats/pclcms:$BITBUCKET_COMMIT
          - docker build -t $IMAGE_NAME -f Dockerfile.prod .
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          - docker push $IMAGE_NAME
        artifacts:
          - dist/**
        
    - step:
        name: Deploy Backend to droplet
        script:
        - export IMAGE_NAME=hanthamarats/pcl-api:$BITBUCKET_COMMIT
        - pipe: atlassian/ssh-run:0.2.2
          variables:
            SSH_USER: $SSH_USER
            SERVER: $SSH_SERVER
            COMMAND: >
              docker stop pclcms-api || true &&
              docker rm pclcms-api || true &&
              docker images | grep hanthamarats/pcl-api | awk '{print $3}' | xargs docker rmi || true &&
              docker run -p $SERVER_PORT:$SERVER_PORT -e SECRET_JWT=$SECRET_JWT -e PORT=$PORT -e API_DOC_URL=$API_DOC_URL -e DATABASE_URL=$DATABASE_URL -e SHADOW_DATABASE_URL=$SHADOW_DATABASE_URL -e NEW_RELIC_APP_NAME=$NEW_RELIC_APP_NAME -e NEW_RELIC_LICENSE_KEY=$NEW_RELIC_LICENSE_KEY -e NEW_RELIC_LICENSE_KEY=$NEW_RELIC_LICENSE_KEY -e USERMANAGE_API=$USERMANAGE_API -d --name pclcms-api $IMAGE_NAME
        services:
        - docker

    - step:
        name: Deploy Frontend to droplet
        script:
        - export IMAGE_NAME=hanthamarats/pclcms:$BITBUCKET_COMMIT
        - pipe: atlassian/ssh-run:0.2.2
          variables:
            SSH_USER: $SSH_USER
            SERVER: $SSH_SERVER
            COMMAND: >
              docker stop pclcms || true &&
              docker rm pclcms || true &&
              docker images | grep hanthamarats/pclcms | awk '{print $3}' | xargs docker rmi || true &&
              docker run --memory=4g -p $SERVER_PORT_FRONEND:$SERVER_PORT_FRONEND -e VITE_API_BASE_URL=$VITE_API_BASE_URL -e VITE_REDIRECT_URL=$VITE_REDIRECT_URL -e VITE_REDIRECT_IMG=$VITE_REDIRECT_IMG -e VITE_USERMANAGE_API=$VITE_USERMANAGE_API -d --name pclcms $IMAGE_NAME
        services:
        - docker