FROM node:lts-slim
RUN apt-get update -y
RUN apt-get install -y openssl
WORKDIR /app
COPY package.json .
RUN npm install --force
COPY . .
EXPOSE 3000
RUN rm -rf node_modules/
RUN npm update --force
CMD ["npm", "run", "dev"]